version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  allow:
    - dependency-type: "all"
  groups:
    all-deps:
      patterns:
        - "*"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
