name: async-signature

on:
  pull_request:
    paths:
      - "async-signature/**"
      - "signature/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: async-signature

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - beta
    steps:
      - uses: actions/checkout@v4
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo check --all-features
      - run: cargo test --release
      - run: cargo test --all-features --release

  minimal-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo update -Z minimal-versions
      - uses: dtolnay/rust-toolchain@stable
      - uses: RustCrypto/actions/cargo-hack-install@master
      - run: rm ../Cargo.toml
      - run: cargo hack test --release --feature-powerset
