name: async-signature

on:
  pull_request:
    paths:
      - "async-signature/**"
      - "signature/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: async-signature

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  no_std:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.75.0 # MSRV
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v4
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.75.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo check --all-features
      - run: cargo test --release
      - run: cargo test --all-features --release

  minimal-versions:
    if: false # Temporarily disabled until signature v2.3.0 is published
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo update -Z minimal-versions
      - uses: dtolnay/rust-toolchain@stable
      - uses: RustCrypto/actions/cargo-hack-install@master
      - run: rm ../Cargo.toml
      - run: cargo hack test --release --feature-powerset
