name: cipher

on:
  pull_request:
    paths:
      - "cipher/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: cipher

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.56.0 # MSRV
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v3
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          profile: minimal
      - run: cargo build --target ${{ matrix.target }}
      - run: cargo build --target ${{ matrix.target }} --features rand_core
      - run: cargo build --target ${{ matrix.target }} --features block-padding

  # TODO: use the reusable workflow after this crate will be part of the
  # toot workspace
  minimal-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
      - uses: RustCrypto/actions/cargo-hack-install@master
      - run: cargo update -Z minimal-versions
      - run: cargo hack test --release --feature-powerset

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.56.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
      - run: cargo check --all-features
      - run: cargo test
      - run: cargo test --features block-padding
      - run: cargo test --features dev
      - run: cargo test --features std
      - run: cargo test --all-features
