name: cipher

on:
  pull_request:
    paths:
      - ".github/workflows/cipher.yml"
      - "cipher/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: cipher

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.85.0 # MSRV
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v4
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - run: cargo build --target ${{ matrix.target }}
      - run: cargo build --target ${{ matrix.target }} --features rand_core
      - run: cargo build --target ${{ matrix.target }} --features block-padding

  # TODO: use the reusable workflow after this crate will be part of the
  # root workspace
  minimal-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@nightly
      - uses: RustCrypto/actions/cargo-hack-install@master
      - run: cargo update -Z minimal-versions
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo hack test --release --feature-powerset

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.85.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo check --all-features
      - run: cargo test
      - run: cargo test --features block-padding
      - run: cargo test --features dev
      - run: cargo test --all-features
